### PR TITLE
Added support for Polylines and tileset polygons (#31)

### PR DESCRIPTION
**Pull request by iUltimateLP**
This PR adds support for polylines (drawn with the polygon tool but it's not a closed polygon so Tiled calls this a "polyline"). It also adds support for the polygons drawn inside the tileset as mentioned in issue #31.

Cheers!

### CODE REVIEW

**Comment by whostheme** [comment]
Great add-in! it's exactly what we need for our game.

Even if it's not exactly needed for tileset polygons, It's a bit unexpected that you didn't parse width and height for tileset objects and leave them zero. After adding 2 lines for this tileset rectangles can also be parsed.

**Comment by lonely-unicorn** [comment]
Hi

I was wondering if this will be fixed?
I really want this feature too

**Comment by TheBoneJarmer** [comment]
Hey guys

I am sorry for the late reply. I have been awfully busy last year with new projects coming up. Will have a look at this and every other remaining issues soon! Also need to pull in the latest Tiled once more and make sure TiledCS is compatible. So stay tuned.

With kind regards,
TheBoneJarmer

**Comment by TheBoneJarmer** [comment]
Hey

I cannot allow merging changes directly into the main branch as the _main_ branch is my stable and production branch. The **develop** branch is being used for continuous development. So in the future please target that one. That said, your changes look really good! 

However, for the sake of easiness I am not going to ask you to re-create the pull request as you also used to main branch of your fork as source branch. So I copied your changes instead. I had to make some modifications to fit the style here and there but you'll notice it is mostly the same.

Anyways, thanks again for the great input! I will release a new version soon that supports _Tiled 1.8.4_ so stay tuned. Will close the pull request.

With kind regards,
TheBoneJarmer

**Pull request closed without merging**
