### PR TITLE
Infinite Layer Support with Chunk Loading

### PR DESCRIPTION
**Pull request by Bryan-Legend**
Replaces #25. Sorry, new to git.

### CODE REVIEW

**Comment by TheBoneJarmer** [comment]
Hi @Bryan-Legend 

I am sorry for the late reply. I have had it very busy last two weeks, a funeral and a upcoming wedding to plan. I will pull your changes today and review that. I do have one question though, do you happen to have a tiledmap and tileset I could use to test with?

I can use my own of course but the fact is that I sometimes not be able to recreate the issue you encountered and sent in a pull request for. Especially with yours here. I do not have a map that big or simply infinite. And while your changes look good, I also like to check out the performance.

With kind regards,
TheBoneJarmer

**Comment by TheBoneJarmer** [comment]
Hi @Bryan-Legend 

One more thing, just a very small piece of advice since you mentioned you are new to git. You are trying to merge in from the main branch of your fork to my develop branch, which is not bad per se. But it is fine because TiledCS is not such a big project. 

But for future projects I highly recommend using the same _source_ branch as _target_ branch. Mainly because the develop branch in other projects may differ like 100s of commits from the main or master branch because in case of big projects, releases do not happen that often and if done, very carefully and thoroughly tested. And in worse case, it may cause conflicts or your changes may not work anymore.

For now it is fine really since the main branch of this repo is at the same _head_ as the develop branch. And the project is not that big so merges happen rather fast.

With kind regards,
TheBoneJarmer

**Comment by TheBoneJarmer** [comment]
Hi @Bryan-Legend 

Finally got some time to look at this. But I am not sure where to start and how to say this politely. But I think your code is a mess. It was rather hard to read and on top of that, you seemed to have replaced existing functionality. While this works for you, which is perfectly fine, I cannot merge this into develop.

That said, I got to ask. How long have you been coding in C#? Because I am happy to give you some feedback on your code here because I think it will help you with the overall code quality in your projects. And obviously I will still add support for infinite layers since that is what you are trying to achieve. It is not like I reject this PR and leave it be. No worries about that.

With kind regards,
TheBoneJarmer

**Comment by Bryan-Legend** [comment]
LOL! I've been coding C# full time since the first beta of C# 1 back in 2000. :)

I agree the code is a mess. I honestly didn't even expect a response to the pull request and wasn't going to invest much time in it.

This code was used a week or two ago in a 48 hour game jam. https://itch.io/jam/utah-indie-game-jam-2021/rate/1277167

During the jam we discovered a major problem with my code. The chunk positions can be negative causing index out of bounds exception. We averted this crisis by unchecking the infinite map option in Tiled and re-saving the map.

**Comment by TheBoneJarmer** [comment]
> During the jam we discovered a major problem with my code. The chunk positions can be negative causing index out of bounds exception. We averted this crisis by unchecking the infinite map option in Tiled and re-saving the map.

Ok, that is good to know. Makes sense actually considering the fact the map is infinite. Also glad to hear you agree about the state of the code. Was worried I insulted you some way. :D

That said, amazing that you used TiledCS for your submission in the game jam! Just gave it a look. Out of 17 your game ended up being number 5. Well done!

**Comment by Bryan-Legend** [comment]
As I've thought about it more I think my whole approach of merging the
chunks was wrong. The data model needs to reflect the sparseness of the map
chunks for efficiency, so they shouldn't be merged at all on map load.

**Comment by TheBoneJarmer** [comment]
I agree. And to tell you the truth, I try to mimic the structure of the TMX file as much as possible. Hence, I would have kept the chunks separated. And I will do so as well. Resulting in a new property called _chunks_ on the _TiledLayer_ class, which is of type _TiledLayerChunck[]_ and will in fact represent all the chunks of data. That is approach I have always used up till now.

**Pull request closed without merging**
