### PR TITLE
Handle reading tiles with rotation and provide functions to easily retrieve the rotations when needed

### PR DESCRIPTION
**Pull request by Goodlyay**
Attempting to merge into "develop" branch this time.

### CODE REVIEW

**Review by TheBoneJarmer — APPROVED** [review]
These changes look really good! I did some more research on the matter and this was indeed a new feature in Tiled 1.5. In any case, there are some things I'd like to change. For example, the models class is not meant to contain logic. At first I was thinking to request a change but I'm not going to bother you with that. The code looks fine and it is a breeze to place it in the right classes so I'm going to do that myself. In any case, thanks a lot!

**Comment by Goodlyay** [comment]
Glad it looks (mostly) good! I did notice that the model class didn't contain any logic, which made my edits seem out of place, but wasn't sure where else to place them. I'll be interested to see how you arrange things.

Also, you probably already noticed but there is a typo in the summary of dataRotationFlags[] (is is). I also forgot to style the curly brackets on GetTileRotation in line with the rest of the project (my editor defaults to same line so I was fighting it).

**Comment by Goodlyay** [comment]
Not sure the timeline of Tiled releases but the rotations have been there since at least 2018, I previously had a project where I had to handle those back then. I do see this on the 1.5 release page which mentions flipping, I think that might be something else that's new though
image

**Comment by TheBoneJarmer** [comment]
Yes, you are right. I mixed something up. I was scrolling through the release notes of Tiled 1.5 as well when I replied, which added support for these flags in maps exported as CSV files. Mix that with the fact I just woke up and than this happens.. My apologies for the confusions.

That being said, I would like show my gratitude you for something else as well. Before your pull request I never heard of these bitwise operators in C#. This is very interesting knowledge for me as I work a lot with binary numbers in my other library, AdvancedSockets. I learnt a great deal looking at your code, which I think is done very beautifully. So hereby, thank you!

**Comment by Goodlyay** [comment]
You're very welcome, I'm glad to have helped someone else learn something new!
Speaking of binary, there was one thing I wanted to mention about it. I have the flags written as binary literals (0b00100000000000000000000000000000 for example) because I like how clear and easy to read/edit it is, but those are only supported in C# 7.0 or later. So if someone wanted to target this project to work with older versions of C#, those would have to be changed to hex literals or something.

**Comment by TheBoneJarmer** [comment]
I too think those are much more clear than hex literals. At least this way you get an actual representation of the binary number. And thank you for the heads up. I added a section in the readme to ensure that those who like to compile the library are aware of the fact they need to use the latest stable dotnet sdk to do so. Better to be safe than sorry.

**Pull request merged**
